---
name: ezbak
services:
    ezbak:
        image: python:3.12-slim-bookworm
        build:
            context: _ROOT_DIR_
            dockerfile: Dockerfile
        container_name: ezbak
        environment:
            - EZBAK_NAME=test
            - EZBAK_HOST_NAME=dev-ezbak
            - EZBAK_ACTION=restore
            - EZBAK_DESTINATIONS=/backups
            - EZBAK_SOURCES=/files/project1,/files/project2
            - EZBAK_RESTORE_DIR=/restore
            - EZBAK_MAX_BACKUPS=4
            - EZBAK_RETENTION_YEARLY=4
            - EZBAK_RETENTION_MONTHLY=4
            - EZBAK_RETENTION_WEEKLY=4
            - EZBAK_RETENTION_DAILY=4
            - EZBAK_RETENTION_HOURLY=4
            - EZBAK_RETENTION_MINUTELY=4
            - EZBAK_LABEL_TIME_UNITS=true
            - EZBAK_LOG_LEVEL=TRACE
            - EZBAK_LOG_FILE=/logs/ezbak.log
            # - EZBAK_COMPRESSION_LEVEL=6
            # - EZBAK_CRON=*/1 * * * *
            - EZBAK_RENAME_FILES=true
            - EZBAK_CLEAN_BEFORE_RESTORE=false
            # - EZBAK_CHOWN_USER=
            # - EZBAK_CHOWN_GROUP=
            # - EZBAK_POSTGRES_HOST=
            # - EZBAK_POSTGRES_PORT=
            # - EZBAK_POSTGRES_USER=
            # - EZBAK_POSTGRES_PASSWORD=
            # - EZBAK_POSTGRES_DB=
            # - EZBAK_USE_POSTGRES=
        volumes:
            - ./source:/source
            - ./backups:/backups
            - ./logs:/logs
            - ./restore:/restore
        develop:
            watch:
                - action: sync+restart
                  path: _ROOT_DIR_/src/
                  target: /app/src/
                  ignore:
                      - .git/
                      - .github/
                      - .dev/
                - action: rebuild
                  path: _ROOT_DIR_/uv.lock
                  target: /app/uv.lock
                - action: rebuild
                  path: _ROOT_DIR_/pyproject.toml
                  target: /app/pyproject.toml
                - action: rebuild
                  path: _ROOT_DIR_/Dockerfile
